version: "3"

services:
  typecho:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/var/www/docker/nginx/conf.d
    ports:
      - "80:80"
    container_name: typecho
    restart: always
    networks:
      - default
    stdin_open: true
    tty: true