version: "3"

services:
  typecho:
    build: 
      context: ./
      dockerfile: Dockerfile
    # volumes: 
    #   - /var/www/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - /var/www/docker/nginx/conf.d/:/var/www/docker/nginx/conf.d/
    ports:
      - "80:80"
    container_name: typecho
    restart: always
    networks:
      - default